import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  <div>
      <Head>
        <title>Rhea Mehta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  </div>
  
  return <Component {...pageProps} />
}

export default MyApp
